services:
  - type: web
    name: familylink
    env: node
    plan: free
    region: singapore
    buildCommand: npm run postinstall && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
